"""Risk scoring + AI report generation.

Risk scoring is deterministic and rule-based (auditable). The AI report is
generated by Claude claude-haiku-4-5-20251001 when an ANTHROPIC_API_KEY is present;
otherwise it falls back to a deterministic template so the app always works.
"""
from __future__ import annotations

import json
import logging
import os

logger = logging.getLogger(__name__)

MODEL_NAME = "claude-haiku-4-5-20251001"
FALLBACK_MODEL_NAME = "injsight-rules-v1"
METHODOLOGY_VERSION = "v1"


# ---------------------------------------------------------------------------
# Risk scoring (deterministic, never replaced)
# ---------------------------------------------------------------------------

def _level(score: int) -> str:
    if score < 35:
        return "Low"
    if score < 60:
        return "Moderate"
    if score < 80:
        return "High"
    return "Very High"


def compute_risk(normalized: dict) -> dict:
    """Compute a deterministic risk score from normalised wallet data."""
    holdings = normalized["holdings"]
    top = holdings[0] if holdings else None
    top_pct = top["percent"] if top else 0
    stable_pct = sum(h["percent"] for h in holdings if h["category"] == "Stablecoin")
    unknown_pct = sum(h["percent"] for h in holdings if h["category"] not in ("Native", "Stablecoin", "Ecosystem", "DeFi"))
    token_count = len(holdings)

    # Sub-scores (0-100, higher = riskier)
    concentration_score = min(int(top_pct), 100)
    diversification_score = max(0, 100 - token_count * 18)
    stablecoin_buffer_score = max(0, 100 - int(stable_pct) * 2)
    volatility_score = min(100, int((100 - stable_pct) * 0.7) + int(unknown_pct))
    activity_score = 30  # placeholder until on-chain activity is wired

    score = int(
        0.35 * concentration_score
        + 0.20 * volatility_score
        + 0.20 * stablecoin_buffer_score
        + 0.15 * diversification_score
        + 0.10 * activity_score
    )
    score = max(0, min(100, score))

    return {
        "score": score,
        "risk_level": _level(score),
        "concentration_score": concentration_score,
        "volatility_score": volatility_score,
        "stablecoin_buffer_score": stablecoin_buffer_score,
        "activity_score": activity_score,
        "diversification_score": diversification_score,
        "methodology_version": METHODOLOGY_VERSION,
    }


# ---------------------------------------------------------------------------
# AI report (Claude when available, rule-based fallback)
# ---------------------------------------------------------------------------

def _build_holdings_summary(holdings: list[dict]) -> str:
    parts = []
    for h in holdings[:6]:
        parts.append(f"{h['symbol']} {h['percent']}% (${h['value_usd']:,.2f})")
    if len(holdings) > 6:
        parts.append(f"... and {len(holdings) - 6} more")
    return ", ".join(parts) if parts else "No holdings"


def _call_claude(normalized: dict, risk: dict) -> dict | None:
    """Call Claude claude-haiku-4-5-20251001 and return parsed JSON report dict.

    Returns None if the API key is missing or any error occurs so the caller
    can fall back to the rule-based report.
    """
    api_key = os.getenv("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        logger.debug("ANTHROPIC_API_KEY not set; using rule-based report.")
        return None

    try:
        import anthropic  # imported lazily so the app starts without the package

        holdings = normalized["holdings"]
        holdings_summary = _build_holdings_summary(holdings)

        prompt = (
            f"You are InjSight AI, an expert Injective DeFi wallet analyst.\n\n"
            f"Analyze this wallet:\n"
            f"- Address: {normalized['address']}\n"
            f"- Total Value: ${normalized['total_value_usd']:,.2f}\n"
            f"- Risk Score: {risk['score']}/100 ({risk['risk_level']})\n"
            f"- Token Count: {normalized['token_count']}\n"
            f"- Holdings: {holdings_summary}\n\n"
            f"Risk Breakdown:\n"
            f"- Concentration: {risk['concentration_score']}/100\n"
            f"- Volatility: {risk['volatility_score']}/100\n"
            f"- Stablecoin Buffer: {risk['stablecoin_buffer_score']}/100\n"
            f"- Diversification: {risk['diversification_score']}/100\n\n"
            f"Return ONLY valid JSON with exactly these keys:\n"
            f"{{\n"
            f'  "summary": "2-3 sentence portfolio overview",\n'
            f'  "concentrationAnalysis": "Analysis of asset concentration",\n'
            f'  "riskExplanation": "Why this risk score was assigned",\n'
            f'  "injectiveContext": "Injective DeFi specific insights",\n'
            f'  "suggestedNextSteps": ["step1", "step2", "step3"],\n'
            f'  "disclaimer": "Standard financial disclaimer"\n'
            f"}}"
        )

        client = anthropic.Anthropic(api_key=api_key)
        response = client.messages.create(
            model=MODEL_NAME,
            max_tokens=800,
            messages=[{"role": "user", "content": prompt}],
        )

        raw_text = response.content[0].text.strip()

        # Strip markdown code fences if Claude wraps the JSON
        if raw_text.startswith("```"):
            raw_text = raw_text.split("```")[1]
            if raw_text.startswith("json"):
                raw_text = raw_text[4:]
            raw_text = raw_text.strip()

        return json.loads(raw_text)

    except Exception as exc:
        logger.warning("Claude API call failed: %s", exc)
        return None


def _rule_based_report(normalized: dict, risk: dict) -> dict:
    """Deterministic rule-based fallback report."""
    holdings = normalized["holdings"]
    top = holdings[0] if holdings else None
    stable_pct = sum(h["percent"] for h in holdings if h["category"] == "Stablecoin")
    top3 = sum(h["percent"] for h in holdings[:3])

    summary = (
        f"This wallet holds {normalized['token_count']} assets worth approximately "
        f"${normalized['total_value_usd']:,.0f}. "
        + (f"Its largest position is {top['symbol']} at {top['percent']}% of the portfolio. " if top else "")
        + "It is an active participant in the Injective ecosystem."
    )
    concentration_analysis = (
        f"The top 3 assets account for {top3:.0f}% of total value. "
        + (
            "This is a highly concentrated portfolio; a single-asset shock would move it significantly. "
            if top3 >= 80
            else "Concentration is within a moderate range. "
        )
        + f"Stablecoins make up {stable_pct:.0f}%, providing a downside buffer."
    )
    risk_explanation = (
        f"Overall risk is {risk['risk_level']} ({risk['score']}/100). "
        f"The dominant factor is asset concentration ({risk['concentration_score']}/100), "
        f"followed by volatility exposure ({risk['volatility_score']}/100). "
        "No custodial or signing access is involved in this analysis."
    )
    injective_context = (
        "Pricing and categorization use Injective ecosystem references. Native INJ exposure is treated as "
        "medium-volatility; stablecoins as low-volatility; unverified tokens raise the risk profile."
    )
    next_steps = []
    if risk["concentration_score"] >= 50:
        next_steps.append("Consider reducing single-asset concentration to lower volatility risk.")
    if stable_pct < 15:
        next_steps.append("A larger stablecoin buffer could cushion market downturns.")
    next_steps.append("Set up risk-change alerts to monitor this wallet over time.")
    next_steps.append("Review any unverified tokens before relying on their valuations.")

    return {
        "summary": summary,
        "concentrationAnalysis": concentration_analysis,
        "riskExplanation": risk_explanation,
        "injectiveContext": injective_context,
        "suggestedNextSteps": next_steps,
        "disclaimer": "Informational only — not financial advice. InjSight AI is read-only and non-custodial.",
    }


def generate_report(normalized: dict, risk: dict) -> dict:
    """Generate an AI report for the wallet.

    Priority order:
    1. OpenRouter AI (primary — fastest, most capable)
    2. Anthropic Claude (secondary fallback)
    3. Rule-based deterministic (always works)
    """
    # 1. Try OpenRouter first (production primary)
    try:
        from app.ai.openrouter_service import generate_wallet_report
        openrouter_result = generate_wallet_report(normalized, risk)
        if openrouter_result and openrouter_result.get("summary"):
            full = openrouter_result
            model_used = "openrouter/" + os.getenv("OPENROUTER_AI_MODEL", "llama-3.3-70b-instruct")
            return {
                "summary":              full.get("summary", ""),
                "concentration_analysis": full.get("concentrationAnalysis", ""),
                "risk_explanation":     full.get("riskExplanation", ""),
                "injective_context":    full.get("injectiveContext", ""),
                "suggested_next_steps": full.get("suggestedNextSteps", []),
                "full_report":          full,
                "model_name":           model_used,
            }
    except Exception as exc:
        logger.warning("OpenRouter report generation failed: %s", exc)

    # 2. Try Anthropic Claude
    claude_result = _call_claude(normalized, risk)
    if claude_result is not None:
        full = claude_result
        model_used = MODEL_NAME
    else:
        # 3. Rule-based fallback — always works
        full = _rule_based_report(normalized, risk)
        model_used = FALLBACK_MODEL_NAME

    return {
        "summary":              full.get("summary", ""),
        "concentration_analysis": full.get("concentrationAnalysis", ""),
        "risk_explanation":     full.get("riskExplanation", ""),
        "injective_context":    full.get("injectiveContext", ""),
        "suggested_next_steps": full.get("suggestedNextSteps", []),
        "full_report":          full,
        "model_name":           model_used,
    }
