import * as React from "react";
import { Info } from "lucide-react";

export function AIReportDisclaimer() {
  return (
    <div className="flex items-start gap-3 p-4 bg-hover/30 border border-border/50 rounded-xl">
      <Info size={16} className="text-text-disabled shrink-0 mt-0.5" />
      <div className="space-y-1">
        <p className="text-[10px] font-bold text-text-disabled uppercase tracking-widest">
          AI Intelligence Disclaimer
        </p>
        <p className="text-[10px] text-text-disabled leading-relaxed italic">
          This report is generated by InjSight AI based on publicly available on-chain data. 
          The analysis provided is for informational purposes only and does not constitute 
          financial, investment, or legal advice. On-chain data can be complex and may 
          contain errors or unverified contract interactions. Always perform your own 
          due diligence before making any financial decisions.
        </p>
      </div>
    </div>
  );
}
