"""initial schema

Revision ID: e3ba70feda4d
Revises: 
Create Date: 2026-05-29 04:24:15.906876
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.common.types


revision: str = 'e3ba70feda4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.common.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alerts',
    sa.Column('id', app.common.types.GUID(), nullable=False),
    sa.Column('user_id', app.common.types.GUID(), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', app.common.types.GUID(), nullable=False),
    sa.Column('user_id', app.common.types.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', app.common.types.GUID(), nullable=False),
    sa.Column('user_id', app.common.types.GUID(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('chain', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=False)

    op.create_table('wallet_analysis_runs',
    sa.Column('id', app.common.types.GUID(), nullable=False),
    sa.Column('user_id', app.common.types.GUID(), nullable=True),
    sa.Column('wallet_id', app.common.types.GUID(), nullable=True),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('chain', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_source', sa.String(length=120), nullable=True),
    sa.Column('normalized_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_analysis_runs_wallet_address'), ['wallet_address'], unique=False)

    op.create_table('ai_reports',
    sa.Column('id', app.common.types.GUID(), nullable=False),
    sa.Column('analysis_run_id', app.common.types.GUID(), nullable=False),
    sa.Column('user_id', app.common.types.GUID(), nullable=True),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('concentration_analysis', sa.Text(), nullable=True),
    sa.Column('risk_explanation', sa.Text(), nullable=True),
    sa.Column('injective_context', sa.Text(), nullable=True),
    sa.Column('suggested_next_steps', sa.JSON(), nullable=True),
    sa.Column('full_report', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['wallet_analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_reports_wallet_address'), ['wallet_address'], unique=False)

    op.create_table('risk_scores',
    sa.Column('id', app.common.types.GUID(), nullable=False),
    sa.Column('analysis_run_id', app.common.types.GUID(), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('concentration_score', sa.Integer(), nullable=True),
    sa.Column('volatility_score', sa.Integer(), nullable=True),
    sa.Column('stablecoin_buffer_score', sa.Integer(), nullable=True),
    sa.Column('activity_score', sa.Integer(), nullable=True),
    sa.Column('diversification_score', sa.Integer(), nullable=True),
    sa.Column('methodology_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['wallet_analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_scores_wallet_address'), ['wallet_address'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_scores_wallet_address'))

    op.drop_table('risk_scores')
    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_reports_wallet_address'))

    op.drop_table('ai_reports')
    with op.batch_alter_table('wallet_analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_analysis_runs_wallet_address'))

    op.drop_table('wallet_analysis_runs')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallets_address'))

    op.drop_table('wallets')
    op.drop_table('usage_events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
